<?php get_header(); ?>
<?php if (hu_elementor_ready_content()) { while (have_posts()) { the_post(); the_content(); } get_footer(); return; } ?>
<section class="page-hero compact" style="background-image:linear-gradient(90deg,rgba(3,19,34,.96),rgba(3,19,34,.45)),url('https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1800&q=80');"><div class="container"><span class="eyebrow">HOSPITALITY SOLUTIONS</span><h1>Uniforms designed for <em>hospitality professionals.</em></h1><p>Appearance, comfort, durability and brand image considered for every role.</p></div></section>
<section class="section light-section"><div class="container"><div class="section-head center reveal"><span class="eyebrow dark">ROLE-BASED SOLUTIONS</span><h2>Choose the team. We’ll help shape the uniform solution.</h2><p>Each hospitality role has different practical needs. These examples show how garments can be matched to the work your team performs.</p></div>
<div class="solution-list">
<article id="kitchen" class="solution-row reveal"><img src="https://unsplash.com/photos/YFK5dBI6Ftc/download?force=true&w=1000" alt="Kitchen team"><div><span class="eyebrow dark">KITCHEN TEAMS</span><h2>Professional kitchen wear built for busy service.</h2><ul><li>Chef coats and kitchen shirts</li><li>Waist and bib aprons</li><li>Comfort-focused garments for long shifts</li><li>Durable branding for repeated use</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a quote for your kitchen team →</a></div></article>
<article id="front-of-house" class="solution-row reverse reveal"><img src="https://unsplash.com/photos/lC8i5_lJqgU/download?force=true&w=1000" alt="Front of house staff"><div><span class="eyebrow dark">FRONT-OF-HOUSE / SERVERS</span><h2>A polished guest-facing look that supports your brand.</h2><ul><li>Server shirts and blouses</li><li>Aprons and coordinated layers</li><li>Consistent logo placement</li><li>Comfortable options for active service</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a quote for your service team →</a></div></article>
<article id="hotel" class="solution-row reveal"><img src="https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80" alt="Hotel staff"><div><span class="eyebrow dark">HOTEL STAFF</span><h2>Coordinated uniforms across guest-facing hotel roles.</h2><ul><li>Reception and concierge uniforms</li><li>Housekeeping and operational apparel</li><li>Suitable outerwear where required</li><li>Brand consistency across departments</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a quote for your hotel team →</a></div></article>
<article id="cafe-bar" class="solution-row reverse reveal"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=80" alt="Cafe and bar staff"><div><span class="eyebrow dark">CAFÉ &amp; BAR TEAMS</span><h2>Modern uniforms with a practical service-first feel.</h2><ul><li>Branded shirts and polos</li><li>Waist and bib aprons</li><li>Caps and hats</li><li>Flexible garments for fast-moving teams</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a quote for your café or bar →</a></div></article>
<article id="catering" class="solution-row reveal"><img src="https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=80" alt="Catering and event staff"><div><span class="eyebrow dark">CATERING &amp; EVENT STAFF</span><h2>A coordinated team presentation for every event.</h2><ul><li>Catering uniforms and service shirts</li><li>Event staff attire</li><li>Branded aprons and practical accessories</li><li>Professional coordinated looks</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a quote for your event team →</a></div></article>
</div></div></section>
<?php get_footer(); ?>