<?php get_header(); ?>
<?php if(hu_elementor_ready_content()){while(have_posts()){the_post();the_content();}get_footer();return;} ?>
<section class="page-hero minimal-page-hero">
  <div class="container"><span class="eyebrow">HOSPITALITY SOLUTIONS</span><h1>Uniforms Designed for <em>Hospitality Professionals</em></h1><p>Uniform choices built around appearance, comfort, durability and brand image for different hospitality roles.</p></div>
</section>
<section class="section light-section">
  <div class="container">
    <div class="section-head center reveal"><span class="eyebrow dark">SOLUTIONS BY ROLE</span><h2>The right garments for each team.</h2><p>This page replaces a traditional portfolio by showing the uniform solutions available for the hospitality roles the business serves.</p></div>
    <div class="solution-list">
      <article id="kitchen" class="solution-row reveal"><img src="https://images.unsplash.com/photo-1759521296144-fe6f2d2dc769?auto=format&fit=crop&w=1200&q=85" alt="Chef wearing white chef uniform"><div><span class="eyebrow dark">KITCHEN TEAMS</span><h2>Professional kitchen uniforms.</h2><p>Practical garments for cooks and chefs working through demanding service periods.</p><ul><li>Chef coats</li><li>Kitchen shirts</li><li>Waist and bib aprons</li><li>Comfort-focused options for long shifts</li><li>Durable embroidery for a consistent brand look</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Request a kitchen team quote →</a></div></article>
      <article id="front-of-house" class="solution-row reverse reveal"><img src="https://images.pexels.com/photos/5920674/pexels-photo-5920674.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Front of house server in professional apron"><div><span class="eyebrow dark">FRONT-OF-HOUSE / SERVERS</span><h2>Polished service uniforms.</h2><p>Guest-facing clothing that keeps the team looking coordinated without compromising movement.</p><ul><li>Server shirts and blouses</li><li>Branded aprons</li><li>Suitable waistcoats or layers</li><li>Consistent logo placement</li><li>Professional front-of-house presentation</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Request a server team quote →</a></div></article>
      <article id="hotel" class="solution-row reveal"><img src="https://images.pexels.com/photos/5371677/pexels-photo-5371677.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Hotel staff in formal hospitality uniform"><div><span class="eyebrow dark">HOTEL STAFF</span><h2>Uniforms for professional hotel teams.</h2><p>A consistent appearance across guest-facing and operational hotel roles.</p><ul><li>Reception and concierge attire</li><li>Housekeeping and operational garments</li><li>Professional shirts, layers and suitable outerwear</li><li>Department-wide branding consistency</li><li>Comfort for daily guest service</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Request a hotel staff quote →</a></div></article>
      <article id="cafe-bar" class="solution-row reverse reveal"><img src="https://images.unsplash.com/photo-1770494347810-5aa9e689f13e?auto=format&fit=crop&w=1200&q=85" alt="Cafe barista wearing a work apron"><div><span class="eyebrow dark">CAFÉ &amp; BAR TEAMS</span><h2>Modern uniforms for fast-moving teams.</h2><p>Flexible workwear that supports a relaxed or premium café and bar identity.</p><ul><li>Branded shirts or polos</li><li>Waist and bib aprons</li><li>Caps and hats</li><li>Practical outer layers</li><li>Easy-to-repeat branding across staff</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Request a café or bar quote →</a></div></article>
      <article id="catering" class="solution-row reveal"><img src="https://images.pexels.com/photos/6817136/pexels-photo-6817136.jpeg?auto=compress&cs=tinysrgb&w=1200" alt="Catering and event service staff in uniform"><div><span class="eyebrow dark">CATERING &amp; EVENT STAFF</span><h2>Coordinated event team presentation.</h2><p>Professional uniforms that make temporary, mobile or event-based teams look consistent.</p><ul><li>Catering shirts and service wear</li><li>Event staff attire</li><li>Branded aprons</li><li>Professional coordinated layers</li><li>Flexible ordering for changing team sizes</li></ul><a class="text-link" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Request a catering team quote →</a></div></article>
    </div>
  </div>
</section>
<section class="section cream-section"><div class="container home-cta-card reveal"><div><span class="eyebrow dark">NEED A CUSTOM SOLUTION?</span><h2>Let’s create a professional uniform program for your team.</h2><p>Send the team type, garments, quantity and logo. We’ll use those details to prepare your quote.</p></div><a class="button button-gold" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a Free Quote →</a></div></section>
<?php get_footer(); ?>