<?php get_header(); ?>
<?php if (hu_elementor_ready_content()) { while (have_posts()) { the_post(); the_content(); } get_footer(); return; } ?>
<section class="page-hero compact" style="background-image:linear-gradient(90deg,rgba(3,19,34,.96),rgba(3,19,34,.42)),url('https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1800&q=80');"><div class="container"><span class="eyebrow">ABOUT</span><h1>Hospitality-focused service. <em>Professional from first quote to reorder.</em></h1><p>Uniform solutions created around the practical needs of restaurants, hotels and hospitality businesses.</p></div></section>
<section class="section light-section"><div class="container two-col about-grid"><div class="reveal"><span class="eyebrow dark">OUR APPROACH</span><h2>We understand that hospitality uniforms need to do more than look good.</h2><p>They need to support long shifts, repeated use, consistent presentation and the brand image guests see every day. Our focus is on combining practical garments with clean, professional embroidery and straightforward service.</p><p>From chef coats and aprons to front-of-house and hotel uniforms, each request is handled around your team’s role, quantity and branding requirements.</p><a class="button button-gold" href="<?php echo esc_url(hu_get_page_url('get-a-quote')); ?>">Get a Free Quote →</a></div><div class="about-visual reveal"><img src="https://unsplash.com/photos/9xObRZdEN7g/download?force=true&w=1000" alt="Professional chef uniform"><div class="about-badge">QUALITY<br><span>EMBROIDERY</span></div></div></div></section>
<section class="section cream-section"><div class="container"><div class="value-grid">
<article class="reveal"><div>01</div><h3>Hospitality Specialization</h3><p>Our service is focused on restaurants, hotels, cafés, bars, catering companies and related hospitality teams.</p></article>
<article class="reveal"><div>02</div><h3>Quality Embroidery</h3><p>Professional branding designed to give hospitality garments a polished, consistent appearance.</p></article>
<article class="reveal"><div>03</div><h3>Fast Service</h3><p>A clear process designed to move efficiently from requirements and quote through approval and production.</p></article>
<article class="reveal"><div>04</div><h3>Flexible Ordering</h3><p>Low minimum orders and easy reordering help teams order according to real staffing needs.</p></article>
</div></div></section>
<section class="section dark-section"><div class="container two-col trust-grid"><div><span class="eyebrow">WHAT MATTERS IN HOSPITALITY</span><h2>Appearance. Comfort. Durability. Brand image.</h2></div><div><p>Uniforms are part of the customer experience. A coordinated team can reinforce professionalism before a word is spoken. Our role is to make the ordering and branding process clear, practical and easy to repeat.</p><p class="service-area">Service area: <strong><?php echo esc_html(get_theme_mod('hu_service_area','Local hospitality businesses')); ?></strong></p></div></div></section>
<?php get_footer(); ?>